export default {
  SELECT_TASK : 'SELECT_TASK',
  CHANGE_FIRST_PATH: 'CHANGE_FIRST_PATH',
  CHANGE_SECOND_PATH: 'CHANGE_SECOND_PATH',
  CHANGE_THIRD_PATH: 'CHANGE_THIRD_PATH',
  NAV_COLLAPSE : 'NAV_COLLAPSE',
  SET_FLOW_LIST: 'SET_FLOW_LIST',
  ADD_NODE: 'ADD_NODE',
  DELETE_NODE: 'DELETE_NODE',
  EDIT_NODE: 'EDIT_NODE',
  SET_INTENTION: 'SET_INTENTION',
  DELETE_INTENTION: 'DELETE_INTENTION',
  ADD_INTENTION: 'ADD_INTENTION',
  EDIT_INTENTION: 'EDIT_INTENTION'
}
